[project]
name = "lib-new"
version = "0.1.1"
description = "Add your description here"
authors = [
    { name = "Ted Romer", email = "tromer@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "cowsay>=6.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
