# We use the same image as the runtime base image so that Python
# version and location matches.
FROM us-west1-docker.pkg.dev/serverless-runtimes/google-22/runtimes/python312 AS builder

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

USER www-data

WORKDIR /pip

ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_PYTHON=/opt/python3.12/bin/python3.12

ENV UV_CACHE_DIR=/tmp/uv/cache
# ENV UV_SYSTEM_PYTHON=1
# ENV UV_PROJECT_ENVIRONMENT=/app 

COPY lib-new lib-new
# RUN uv --directory=lib-new export --format requirements.txt --no-editable --frozen | sed -e 's@^\.@# Elided: .@' > /tmp/lib-new-constraints.txt
# RUN uv --directory=lib-new build -b /tmp/lib-new-constraints.txt -o /tmp/dist --wheel
RUN cd lib-new && UV_PROJECT_ENVIRONMENT=/tmp/lib-new/venv uv sync --frozen --no-dev --compile-bytecode
RUN find /tmp/lib-new/venv -type f

COPY app-new app-new
# RUN uv --directory=lib-new export --format requirements.txt --no-editable --frozen | sed -e 's@^\.@# Elided: .@' > /tmp/lib-new-constraints.txt
# RUN uv --directory=lib-new build -b /tmp/lib-new-constraints.txt -o /tmp/dist --wheel
RUN cd app-new && UV_PROJECT_ENVIRONMENT=/tmp/app-new/venv uv sync --frozen --no-dev --compile-bytecode
RUN find /tmp/app-new/venv -type f

# RUN uv --directory=app-new export --format requirements.txt --no-editable --frozen | sed -e 's@^\.@# Elided: .@' > /tmp/app-new-constraints.txt
# RUN uv --directory=app-new build -b /tmp/app-new-constraints.txt -o /tmp/dist --wheel
# RUN pip install --no-cache-dir --prefix=python-packages /tmp/dist/*.whl && \
#     PYTHONPATH=python-packages/lib/python3.12/site-packages python -m pip freeze
# 2>/dev/null || true  ???
RUN mkdir -p python-packages/lib/python3.12/site-packages/ python-packages/bin/
RUN cp -r /tmp/lib-new/venv/lib/python3.12/site-packages/* python-packages/lib/python3.12/site-packages/
RUN cp -r /tmp/app-new/venv/lib/python3.12/site-packages/* python-packages/lib/python3.12/site-packages/
RUN cp -r /tmp/lib-new/venv/bin/* python-packages/bin/
RUN cp -r /tmp/app-new/venv/bin/* python-packages/bin/
RUN find python-packages

# Run
FROM scratch
COPY --from=builder /pip/python-packages /opt/python
COPY . /workspace/

ENV PYTHONPATH=/opt/python/lib/python3.12/site-packages
ENV PATH=/opt/python/bin:$PATH

WORKDIR /workspace

CMD ["app-new"]
