[project]
name = "uv-monorepo-example"
version = "0.1.0"
description = "uv monorepo example"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]

[tool.uv.workspace]
members = ["libs/*/", "apps/*/"]
