[project]
name = "a2"
version = "0.1.1"
requires-python = ">=3.11"
dependencies = [
    "l2",
]

[project.scripts]
a2 = "a2:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# [tool.uv.sources]
# lib-new = { path = "../lib-new", editable = true }
