# Simulate deployed service for local testing.
FROM us-west1-docker.pkg.dev/serverless-runtimes/google-22/runtimes/python312

COPY --from=a1 /workspace /workspace

ENV PYTHONPATH=/workspace/.venv/lib/python3.12/site-packages
ENV PATH=/workspace/.venv/bin:$PATH

CMD ["a1"]
