[project]
name = "a1"
version = "0.1.1"
requires-python = ">=3.11"
dependencies = [
    "l1",
]

[dependency-groups]
dev = [
    "pytest>0",
]

[project.scripts]
a1 = "a1:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
